version: "3.7"
services:
    app:
        build:
            args:
                user: ronan
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: api-cardapio
        container_name: api-cardapio-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - api-cardapio

    db:
        image: postgres:latest
        container_name: api-cardapio-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./docker-compose/postgres:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        networks:
            - api-cardapio

    nginx:
        image: nginx:alpine
        container_name: api-cardapio-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - api-cardapio

networks:
    api-cardapio:
        driver: bridge
